routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','/login');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::resource('customers', App\Http\Controllers\CustomerController::class);

Route::resource('products', App\Http\Controllers\ProductController::class);

Route::resource('orders', App\Http\Controllers\OrderController::class);

Route::resource('boutiques', App\Http\Controllers\BoutiqueController::class);

Route::resource('orderLitiges', App\Http\Controllers\OrderLitigeController::class);
Route::get('orderLitiges/rejected/{id}', [App\Http\Controllers\OrderLitigeController::class, 'rejected'])->name('orderLitiges.rejected');
Route::get('orderLitiges/approved/{id}', [App\Http\Controllers\OrderLitigeController::class, 'approved'])->name('orderLitiges.approved');
Route::get('orderLitiges/solved/{id}', [App\Http\Controllers\OrderLitigeController::class, 'solved'])->name('orderLitiges.solved');

app/Models/OrderLitige.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 * Class OrderLitige
 * @package App\Models
 * @version August 18, 2021, 4:47 pm UTC
 *
 * @property integer $order_id
 * @property integer $customer_id
 * @property integer $seller_id
 * @property string $customer_solution
 * @property string $seller_solution
 * @property string $seller_note
 * @property string $final_litige_solution
 * @property boolean $litige_accepted
 * @property integer $feedback_id
 * @property string $litige_rejected_reason
 * @property boolean $solved
 * @property boolean $is_completed
 * @property boolean $is_waiting_admin_acceptation
 */
class OrderLitige extends Model
{
    use SoftDeletes;

    use HasFactory;
    protected $appends = ['customer', 'seller'];


    public $table = 'order_litiges';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    protected $dates = ['deleted_at'];

    // public $fillable = [
    //     'order_id',
    //     'customer_id',
    //     'seller_id',
    //     'customer_solution',
    //     'seller_solution',
    //     'seller_note',
    //     'final_litige_solution',
    //     'litige_accepted',
    //     'feedback_id',
    //     'litige_rejected_reason',
    //     'solved',
    //     'is_completed',
    //     'is_waiting_admin_acceptation'
    // ];

    public $guarded = [];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'order_id' => 'integer',
        'customer_id' => 'integer',
        'seller_id' => 'integer',
        'customer_solution' => 'string',
        'seller_solution' => 'string',
        'seller_note' => 'string',
        'final_litige_solution' => 'string',
        'litige_accepted' => 'boolean',
        'feedback_id' => 'integer',
        'litige_rejected_reason' => 'string',
        'solved' => 'boolean',
        'is_completed' => 'boolean',
        'is_waiting_admin_acceptation' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'order_id' => 'nullable',
        'customer_id' => 'nullable',
        'seller_id' => 'nullable',
        'customer_solution' => 'nullable|string|max:225',
        'seller_solution' => 'nullable|string|max:225',
        'seller_note' => 'nullable|string',
        'final_litige_solution' => 'nullable|string|max:225',
        'litige_accepted' => 'nullable|boolean',
        'feedback_id' => 'nullable',
        'litige_rejected_reason' => 'nullable|string',
        'solved' => 'nullable|boolean',
        'is_completed' => 'nullable|boolean',
        'is_waiting_admin_acceptation' => 'nullable|boolean',
        'created_at' => 'nullable',
        'updated_at' => 'nullable',
        'deleted_at' => 'nullable'
    ];

    public function getCustomerAttribute(){
        $customer = Customer::where('id', $this->customer_id)->first();
        return $customer;
    }

    public function getSellerAttribute(){
        $customer = Customer::where('id', $this->seller_id)->first();
        return $customer;
    }


}

app/Http/Controllers/OrderLitigeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrderLitigeRequest;
use App\Http\Requests\UpdateOrderLitigeRequest;
use App\Repositories\OrderLitigeRepository;
use App\Http\Controllers\AppBaseController;
use App\Models\OrderLitige;
use Illuminate\Http\Request;
use Flash;
use Response;

class OrderLitigeController extends AppBaseController
{
    /** @var  OrderLitigeRepository */
    private $orderLitigeRepository;

    public function __construct(OrderLitigeRepository $orderLitigeRepo)
    {
        $this->orderLitigeRepository = $orderLitigeRepo;
    }

    /**
     * Display a listing of the OrderLitige.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $orderLitiges = $this->orderLitigeRepository->paginate(10);

        return view('order_litiges.index')
            ->with('orderLitiges', $orderLitiges);
    }

    /**
     * Show the form for creating a new OrderLitige.
     *
     * @return Response
     */
    public function create()
    {
        return view('order_litiges.create');
    }

    /**
     * Store a newly created OrderLitige in storage.
     *
     * @param CreateOrderLitigeRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderLitigeRequest $request)
    {
        $input = $request->all();

        $orderLitige = $this->orderLitigeRepository->create($input);

        Flash::success('Order Litige saved successfully.');

        return redirect(route('orderLitiges.index'));
    }

    /**
     * Display the specified OrderLitige.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $orderLitige = $this->orderLitigeRepository->find($id);

        if (empty($orderLitige)) {
            Flash::error('Order Litige not found');

            return redirect(route('orderLitiges.index'));
        }

        return view('order_litiges.show')->with('orderLitige', $orderLitige);
    }

    /**
     * Show the form for editing the specified OrderLitige.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $orderLitige = $this->orderLitigeRepository->find($id);

        if (empty($orderLitige)) {
            Flash::error('Order Litige not found');

            return redirect(route('orderLitiges.index'));
        }

        return view('order_litiges.edit')->with('orderLitige', $orderLitige);
    }

    /**
     * Update the specified OrderLitige in storage.
     *
     * @param int $id
     * @param UpdateOrderLitigeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderLitigeRequest $request)
    {
        $orderLitige = $this->orderLitigeRepository->find($id);

        if (empty($orderLitige)) {
            Flash::error('Order Litige not found');

            return redirect(route('orderLitiges.index'));
        }

        $orderLitige = $this->orderLitigeRepository->update($request->all(), $id);

        Flash::success('Order Litige updated successfully.');

        return redirect(route('orderLitiges.index'));
    }

    /**
     * Remove the specified OrderLitige from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $orderLitige = $this->orderLitigeRepository->find($id);

        if (empty($orderLitige)) {
            Flash::error('Order Litige not found');

            return redirect(route('orderLitiges.index'));
        }

        $this->orderLitigeRepository->delete($id);

        Flash::success('Order Litige deleted successfully.');

        return redirect(route('orderLitiges.index'));
    }


    public function rejected($id){
        $orderLitige = OrderLitige::findOrFail($id);
        $orderLitige->litige_accepted = false;
        $orderLitige->is_waiting_admin_acceptation = false;
        $orderLitige->save();
        toastr()->error('Rejeté !', 'Changement de status du litige');

        return back();
    }

    public function approved($id){
        $orderLitige = OrderLitige::findOrFail($id);
        $orderLitige->litige_accepted = true;
        $orderLitige->is_waiting_admin_acceptation = false;
        $orderLitige->save();
        toastr()->success('Approuvé', 'Changement de status du litige');

        return back();
    }

    public function solved($id){
        $orderLitige = OrderLitige::findOrFail($id);
        $orderLitige->solved = true;
        $orderLitige->save();
        toastr()->info('Résolue', 'Changement de status du litige');

        return back();
    }
}

resources/views/order_litiges/create.blade.php
@extends('layouts.app')
@section('title')
    Create Order Litige 
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h3 class="page__heading m-0">New Order Litige</h3>
            <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                <a href="{{ route('orderLitiges.index') }}" class="btn btn-primary">Back</a>
            </div>
        </div>
        <div class="content">
            @include('stisla-templates::common.errors')
            <div class="section-body">
               <div class="row">
                   <div class="col-lg-12">
                       <div class="card">
                           <div class="card-body ">
                                {!! Form::open(['route' => 'orderLitiges.store']) !!}
                                    <div class="row">
                                        @include('order_litiges.fields')
                                    </div>
                                {!! Form::close() !!}
                           </div>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </section>
@endsection

resources/views/order_litiges/edit.blade.php
@extends('layouts.app')
@section('title')
    Editer | Litige
@endsection
@section('content')
    <section class="section">
            <div class="section-header">
                <h3 class="page__heading m-0">Editer | Litige</h3>
                <div class="filter-container section-header-breadcrumb row justify-content-md-end">
                    <a href="{{ route('orderLitiges.index') }}"  class="btn btn-primary">Retour</a>
                </div>
            </div>
  <div class="content">
              @include('stisla-templates::common.errors')
              <div class="section-body">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-body ">
                                    {!! Form::model($orderLitige, ['route' => ['orderLitiges.update', $orderLitige->id], 'method' => 'patch']) !!}
                                        <div class="row">
                                            @include('order_litiges.fields')
                                        </div>

                                    {!! Form::close() !!}
                            </div>
                         </div>
                    </div>
                 </div>
              </div>
   </div>
  </section>
@endsection

resources/views/order_litiges/fields.blade.php
<!-- Order Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order_id', 'Order Id:') !!}
    {!! Form::number('order_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Customer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    {!! Form::number('customer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Seller Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('seller_id', 'Seller Id:') !!}
    {!! Form::number('seller_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Customer Solution Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_solution', 'Customer Solution:') !!}
    {!! Form::text('customer_solution', null, ['class' => 'form-control','maxlength' => 225,'maxlength' => 225,'maxlength' => 225]) !!}
</div>

<!-- Seller Solution Field -->
<div class="form-group col-sm-6">
    {!! Form::label('seller_solution', 'Seller Solution:') !!}
    {!! Form::text('seller_solution', null, ['class' => 'form-control','maxlength' => 225,'maxlength' => 225,'maxlength' => 225]) !!}
</div>

<!-- Seller Note Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('seller_note', 'Seller Note:') !!}
    {!! Form::textarea('seller_note', null, ['class' => 'form-control']) !!}
</div>

<!-- Final Litige Solution Field -->
<div class="form-group col-sm-6">
    {!! Form::label('final_litige_solution', 'Final Litige Solution:') !!}
    {!! Form::text('final_litige_solution', null, ['class' => 'form-control','maxlength' => 225,'maxlength' => 225,'maxlength' => 225]) !!}
</div>

<!-- Litige Accepted Field -->
<div class="form-group col-sm-6">
    {!! Form::label('litige_accepted', 'Litige Accepted:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('litige_accepted', 0) !!}
        {!! Form::checkbox('litige_accepted', '1', null) !!}
    </label>
</div>


<!-- Feedback Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('feedback_id', 'Feedback Id:') !!}
    {!! Form::number('feedback_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Litige Rejected Reason Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('litige_rejected_reason', 'Litige Rejected Reason:') !!}
    {!! Form::textarea('litige_rejected_reason', null, ['class' => 'form-control']) !!}
</div>

<!-- Solved Field -->
<div class="form-group col-sm-6">
    {!! Form::label('solved', 'Solved:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('solved', 0) !!}
        {!! Form::checkbox('solved', '1', null) !!}
    </label>
</div>


<!-- Is Completed Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_completed', 'Is Completed:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('is_completed', 0) !!}
        {!! Form::checkbox('is_completed', '1', null) !!}
    </label>
</div>


<!-- Is Waiting Admin Acceptation Field -->
<div class="form-group col-sm-6">
    {!! Form::label('is_waiting_admin_acceptation', 'Is Waiting Admin Acceptation:') !!}
    <label class="checkbox-inline">
        {!! Form::hidden('is_waiting_admin_acceptation', 0) !!}
        {!! Form::checkbox('is_waiting_admin_acceptation', '1', null) !!}
    </label>
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('orderLitiges.index') }}" class="btn btn-light">Cancel</a>
</div>

resources/views/order_litiges/index.blade.php
@extends('layouts.app')
@section('title')
    Gestions | Litiges
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Gestions | Litiges</h1>
            <div class="section-header-breadcrumb">
                <a href="{{ route('orderLitiges.create')}}" class="btn btn-primary form-btn">Gestions | Litiges <i class="fas fa-plus"></i></a>
            </div>
        </div>
    <div class="section-body">
       <div class="card">
            <div class="card-body">
                @include('order_litiges.table')
            </div>
       </div>
   </div>

    </section>
@endsection

resources/views/order_litiges/show.blade.php
@extends('layouts.app')
@section('title')
    Details - Litiges
@endsection
@section('content')
    <section class="section">
        <div class="section-header">
        <h1>Details - Litiges</h1>
        <div class="section-header-breadcrumb">
            <a href="{{ route('orderLitiges.index') }}"
                 class="btn btn-primary form-btn float-right">Retour</a>
        </div>
      </div>
   @include('stisla-templates::common.errors')
    <div class="section-body">
           <div class="card">
            <div class="card-body">
                    @include('order_litiges.show_fields')
            </div>
            </div>
    </div>
    </section>
@endsection

resources/views/order_litiges/show_fields.blade.php
<div class="container">
    <div class="row">
        <!-- Order Id Field -->

      <!-- Order Id Field -->
        <div class="col-md-6">
            {!! Form::label('order_id', 'Numéro de la commande:') !!}
            <p>{{ $orderLitige->order_id }}</p>
        </div>

        <!-- Customer Id Field -->
        <div class="col-md-6">
            {!! Form::label('customer_id', 'Utilisteur:') !!}
            <p>{{ $orderLitige->customer ? $orderLitige->customer->name : 'donnée manquante' }}</p>
        </div>

        <!-- Seller Id Field -->
        <div class="col-md-6">
            {!! Form::label('seller_id', 'Vendeur :') !!}
            <p>{{ $orderLitige->seller ? $orderLitige->seller->name : 'donnée manquante' }}</p>
        </div>

        <!-- Customer Solution Field -->
        <div class="col-md-6">
            {!! Form::label('customer_solution', 'Solution de l\'utilisateur:') !!}
            <p>{{ $orderLitige->customer_solution }}</p>
        </div>

        <!-- Seller Solution Field -->
        <div class="col-md-6">
            {!! Form::label('seller_solution', 'Solution du vendeur:') !!}
            <p>{{ $orderLitige->seller_solution }}</p>
        </div>

        <!-- Seller Note Field -->
        <div class="col-md-6">
            {!! Form::label('seller_note', 'Remarque du venduer:') !!}
            <p>{{ $orderLitige->seller_note }}</p>
        </div>

        <!-- Final Litige Solution Field -->
        <div class="col-md-6">
            {!! Form::label('final_litige_solution', 'Solution final du litige:') !!}
            <p>{{ $orderLitige->final_litige_solution }}</p>
        </div>

        <!-- Litige Accepted Field -->
        <div class="col-md-6">
            {!! Form::label('litige_accepted', 'Status du Litige :') !!}
            <p>{{ $orderLitige->litige_accepted == true ? 'Oui': 'Non' }}</p>
        </div>

        <!-- Feedback Id Field -->
        <div class="col-md-6">
            {!! Form::label('feedback_id', 'Feedback Id:') !!}
            <p>{{ $orderLitige->feedback_id }}</p>
        </div>

        <!-- Litige Rejected Reason Field -->
        <div class="col-md-6">
            {!! Form::label('litige_rejected_reason', 'Raison de refus:') !!}
            <p>{{ $orderLitige->litige_rejected_reason }}</p>
        </div>

        <!-- Solved Field -->
        <div class="col-md-6">
            {!! Form::label('solved', 'Résolu ?:') !!}
            <p>{{ $orderLitige->solved == true ? 'Oui': 'Non'  }}</p>
        </div>

        <!-- Is Completed Field -->
        <div class="col-md-6">
            {!! Form::label('is_completed', 'Est terminé ?:') !!}
            <p>{{ $orderLitige->is_completed == true ? 'Oui': 'Non' }}</p>
        </div>

        <!-- Is Waiting Admin Acceptation Field -->
        <div class="col-md-6">
            {!! Form::label('is_waiting_admin_acceptation', 'En attente de d\'approbation:') !!}
            <p>{{ $orderLitige->is_waiting_admin_acceptation == true ? 'Oui': 'Non' }}</p>
        </div>
           <!-- Is Waiting Admin Acceptation Field -->
        <div class="col-md-6">
        </div>

        <div class="col-md-4">
            <button class="btn btn-primary">
                Définir la solutions du litige
            </button>
        </div>

        <div class="col-md-4">
            <button class="btn btn-success">
               Accepter
            </button>
        </div>

        <div class="col-md-4">
            <button class="btn btn-danger">
                Refuser
            </button>
        </div>

    </div>



</div>

@section('scripts')
    <script>

    </script>
@endsection

resources/views/order_litiges/table.blade.php
<div class="table-responsive">
    <table class="table" id="orderLitiges-table">
        <thead>
            <tr>
                <th>#ID Numéro de la commande </th>
                <th>Utilisateurs </th>
                <th>Vendeur </th>
                <th>Solution de l'acheteur</th>
                <th>Solution du vendeur</th>
                <th>Seller Note</th>
                <th>Solution Final du Litige</th>
                <th>Litige Accepted</th>
                <th>Feedback Id</th>
                <th>raison de refus du Litige</th>
                <th>Soluttion</th>
                <th>Est Terminé</th>
                <th>En attende d'acceptation</th>
                <th colspan="3">Action</th>

            </tr>
        </thead>
        <tbody>
        @foreach($orderLitiges as $orderLitige)
            <tr>
                <td>{{ $orderLitige->order_id }}</td>
                <td>{{ $orderLitige->customer ? $orderLitige->customer->name: "Donnée manquante ..."}}</td>
                <td>{{ $orderLitige->seller ? $orderLitige->seller->name: "Donnée manquante ..." }}</td>
                <td>{{ \Illuminate\Support\Str::limit($orderLitige->customer_solution, 30, '....') }}</td>
                <td>{{ \Illuminate\Support\Str::limit($orderLitige->seller_solution, 30, '....') }}</td>
                <td>{{ \Illuminate\Support\Str::limit($orderLitige->seller_note, 30, '....') }}</td>
                <td>{{ \Illuminate\Support\Str::limit($orderLitige->final_litige_solution, 30, '....') }}</td>
                <td>
                    @if($orderLitige->litige_accepted == true)
                        <button class="btn btn-success" disabled>
                            Accepté
                        </button>
                    @else
                        <button class="btn btn-secondary" disabled>
                            Non Accépté
                        </button>
                    @endif
                </td>
                <td>{{ $orderLitige->feedback_id }}</td>
                <td>{{ $orderLitige->litige_rejected_reason }}</td>
                <td>{{ $orderLitige->solved }}</td>

                <td>
                    @if($orderLitige->is_completed == true)
                        <button class="btn btn-success" disabled>
                            Approuver
                        </button>
                    @else
                        <button class="btn btn-secondary" disabled>
                            Non Approuver
                        </button>
                    @endif
                </td>

                <td>{{ $orderLitige->is_waiting_admin_acceptation == true ? 'Oui' : 'Non' }}</td>
                <td class=" text-center">
                    {!! Form::open(['route' => ['orderLitiges.destroy', $orderLitige->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('orderLitiges.solved', [$orderLitige->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-check"></i></a>
                        <a href="{!! route('orderLitiges.approved', [$orderLitige->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-certificate"></i></a>
                        <a href="{!! route('orderLitiges.rejected', [$orderLitige->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-times"></i></a>
                        <a href="{!! route('orderLitiges.show', [$orderLitige->id]) !!}" class='btn btn-light action-btn '><i class="fa fa-eye"></i></a>
                        <a href="{!! route('orderLitiges.edit', [$orderLitige->id]) !!}" class='btn btn-warning action-btn edit-btn'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger action-btn delete-btn', 'onclick' => 'return confirm("Are you sure want to delete this record ?")']) !!}
                    </div>
                    {!! Form::close() !!}
                </td>

            </tr>
        @endforeach
        </tbody>
    </table>
</div>